#!/bin/sh
mkdir -p /lost+found
mkdir -p /data/tsweb
mkdir -p /data/test
mkdir -p /data/build
mkdir -p /data/hdfs_staging
mkdir -p /data/reporting
mkdir -p /data/mapr
mkdir -p /data/webcache
mkdir -p /data/hadoop_tmp
mkdir -p /data/crawler
mkdir -p /data/harvesters
mkdir -p /data/tsweb/harvesters
mkdir -p /data/tsweb/harvesters/SpyEyeBinaryURLs
mkdir -p /data/tsweb/harvesters/SpyEyeDomainBlockList
mkdir -p /data/tsweb/harvesters/ZeusDomainBlockList
mkdir -p /data/tsweb/harvesters/ZeusBinaryURLs
mkdir -p /data/tsweb/harvesters/ZeusArtro
mkdir -p /data/tsweb/harvesters/SpyEyeConfigURLs
mkdir -p /data/tsweb/harvesters/SpyEyeDropZones
mkdir -p /data/tsweb/harvesters/wwuncat
mkdir -p /data/tsweb/harvesters/ZeusDropZones
mkdir -p /data/tsweb/harvesters/SEOTrends
mkdir -p /data/tsweb/harvesters/ZeusConfigURLs
mkdir -p /data/test/apkparser
mkdir -p /data/test/apkparser/results
mkdir -p /data/build/staging
mkdir -p /data/build/infofile
mkdir -p /data/build/ticketing
mkdir -p /data/build/archive
mkdir -p /data/build/sa_import
mkdir -p /data/build/sa_export
mkdir -p /data/build/harvesters
mkdir -p /data/build/staging/xl
mkdir -p /data/build/staging/ns
mkdir -p /data/build/staging/tsc
mkdir -p /data/build/staging/ts
mkdir -p /data/build/staging/sl
mkdir -p /data/build/infofile/xl
mkdir -p /data/build/infofile/ns
mkdir -p /data/build/infofile/tsc
mkdir -p /data/build/infofile/ts
mkdir -p /data/build/infofile/sl
mkdir -p /data/build/archive/xl
mkdir -p /data/build/archive/ns
mkdir -p /data/build/archive/tsc
mkdir -p /data/build/archive/ts
mkdir -p /data/build/archive/sl
mkdir -p /data/build/sa_import/zeus
mkdir -p /data/build/sa_import/artro
mkdir -p /data/build/harvesters/drtuf
mkdir -p /data/build/harvesters/sfoh
mkdir -p /data/build/harvesters/blist_generator
mkdir -p /data/build/harvesters/MRTUF
mkdir -p /data/build/harvesters/netcraft
mkdir -p /data/build/harvesters/Zonefile
mkdir -p /data/build/harvesters/crawler
mkdir -p /data/build/harvesters/sfoh/raiden_export
mkdir -p /data/build/harvesters/sfoh/repper
mkdir -p /data/build/harvesters/sfoh/results
mkdir -p /data/build/harvesters/sfoh/raiden_export/source
mkdir -p /data/build/harvesters/sfoh/raiden_export/results
mkdir -p /data/build/harvesters/sfoh/raiden_export/source/archive
mkdir -p /data/build/harvesters/sfoh/raiden_export/source/working
mkdir -p /data/build/harvesters/sfoh/repper/source
mkdir -p /data/build/harvesters/sfoh/repper/source/archive
mkdir -p /data/build/harvesters/sfoh/repper/source/working
mkdir -p /data/build/harvesters/blist_generator/transfer
mkdir -p /data/build/harvesters/crawler/marxav
mkdir -p /data/hdfs_staging/shared
mkdir -p /data/hdfs_staging/shared/harvesters
mkdir -p /data/mapr/data
mkdir -p /data/mapr/data/tsweb
mkdir -p /data/mapr/data/wps_virus
mkdir -p /data/mapr/data/tsweb/harvesters
mkdir -p /data/mapr/data/tsweb/harvesters/PalevoTopCCIPsContacted
mkdir -p /data/mapr/data/tsweb/harvesters/APWG
mkdir -p /data/mapr/data/tsweb/harvesters/drtuf
mkdir -p /data/mapr/data/tsweb/harvesters/malwaredomainlist
mkdir -p /data/mapr/data/tsweb/harvesters/Malc0de
mkdir -p /data/mapr/data/tsweb/harvesters/saartemis
mkdir -p /data/mapr/data/tsweb/harvesters/MarxAV
mkdir -p /data/mapr/data/tsweb/harvesters/malwaredomainlistfull
mkdir -p /data/mapr/data/tsweb/harvesters/FaceBookBlackList
mkdir -p /data/mapr/data/tsweb/harvesters/NAMESERVER
mkdir -p /data/mapr/data/tsweb/harvesters/malc0de
mkdir -p /data/mapr/data/tsweb/harvesters/rsatrojan
mkdir -p /data/mapr/data/tsweb/harvesters/MobileSeed
mkdir -p /data/mapr/data/tsweb/harvesters/CleanMxPhishing
mkdir -p /data/mapr/data/tsweb/harvesters/MobileParsed
mkdir -p /data/mapr/data/tsweb/harvesters/Repper
mkdir -p /data/mapr/data/tsweb/harvesters/drtufalligator
mkdir -p /data/mapr/data/tsweb/harvesters/CSirt
mkdir -p /data/mapr/data/tsweb/harvesters/rsaphishing
mkdir -p /data/mapr/data/tsweb/harvesters/dwa_test
mkdir -p /data/mapr/data/tsweb/harvesters/MUTE
mkdir -p /data/mapr/data/tsweb/harvesters/CleanMxVirus
mkdir -p /data/mapr/data/tsweb/harvesters/PalevoRecentMalware
mkdir -p /data/mapr/data/tsweb/harvesters/MWGMalware
mkdir -p /data/mapr/data/tsweb/harvesters/MalwareBlacklist
mkdir -p /data/mapr/data/tsweb/harvesters/SAArtemis
mkdir -p /data/mapr/data/tsweb/harvesters/repper
mkdir -p /data/mapr/data/tsweb/harvesters/FraudWatch
mkdir -p /data/mapr/data/tsweb/harvesters/wwuncat
mkdir -p /data/mapr/data/tsweb/harvesters/MRTUF
mkdir -p /data/mapr/data/tsweb/harvesters/DomainRegistration
mkdir -p /data/mapr/data/tsweb/harvesters/TOR
mkdir -p /data/mapr/data/tsweb/harvesters/jpantiphishing
mkdir -p /data/mapr/data/tsweb/harvesters/PalevoProactive
mkdir -p /data/mapr/data/tsweb/harvesters/PalevoTopCCServers
mkdir -p /data/mapr/data/tsweb/harvesters/PalevoCombined
mkdir -p /data/mapr/data/tsweb/harvesters/RepperDomainHarvesterResults
mkdir -p /data/mapr/data/tsweb/harvesters/zonator_gp
mkdir -p /data/mapr/data/tsweb/harvesters/MWGDCCTelemetry
mkdir -p /data/mapr/data/tsweb/harvesters/Zonefile
mkdir -p /data/mapr/data/tsweb/harvesters/PassiveDNS
mkdir -p /data/mapr/data/tsweb/harvesters/CleanMxPortal
mkdir -p /data/mapr/data/tsweb/harvesters/scumware
mkdir -p /data/mapr/data/tsweb/harvesters/seo
mkdir -p /data/mapr/data/tsweb/harvesters/malwareurls
mkdir -p /data/mapr/data/tsweb/harvesters/Malc0de/suresh_backup
mkdir -p /data/mapr/data/tsweb/harvesters/Repper/result
mkdir -p /data/mapr/data/tsweb/harvesters/repper/result
mkdir -p /data/mapr/data/tsweb/harvesters/wwuncat/result
mkdir -p /data/webcache/harvester
mkdir -p /data/webcache/harvester/FaceBookBlackList
mkdir -p /data/hadoop_tmp/test
mkdir -p /data/hadoop_tmp/pending
mkdir -p /data/hadoop_tmp/shared
mkdir -p /data/hadoop_tmp/archive
mkdir -p /data/hadoop_tmp/shared/harvesters
mkdir -p /data/harvesters/drtuf
mkdir -p /data/harvesters/mute_export
mkdir -p /data/harvesters/sfoh
mkdir -p /data/harvesters/zonator
mkdir -p /data/harvesters/phishtank
mkdir -p /data/harvesters/McAfeeSecure
mkdir -p /data/harvesters/artemis
mkdir -p /data/harvesters/bitdefender
mkdir -p /data/harvesters/IWF
mkdir -p /data/harvesters/blist_generator
mkdir -p /data/harvesters/seo_harvester
mkdir -p /data/harvesters/ncmec_current
mkdir -p /data/harvesters/dwa_test
mkdir -p /data/harvesters/ncmec
mkdir -p /data/harvesters/repper
mkdir -p /data/harvesters/wwuncat
mkdir -p /data/harvesters/markmonitor
mkdir -p /data/harvesters/phishing_drop
mkdir -p /data/harvesters/MRTUF
mkdir -p /data/harvesters/DomainRegistration
mkdir -p /data/harvesters/bitdefender_export
mkdir -p /data/harvesters/iwf
mkdir -p /data/harvesters/netcraft
mkdir -p /data/harvesters/zonator_gp
mkdir -p /data/harvesters/Zonefile
mkdir -p /data/harvesters/drs
mkdir -p /data/harvesters/crawler
mkdir -p /data/harvesters/mute_export/archive
mkdir -p /data/harvesters/mute_export/working
mkdir -p /data/harvesters/sfoh/mobile
mkdir -p /data/harvesters/sfoh/MWGMalware
mkdir -p /data/harvesters/sfoh/repper
mkdir -p /data/harvesters/sfoh/socialmedia
mkdir -p /data/harvesters/sfoh/wwuncat
mkdir -p /data/harvesters/sfoh/mobile/source
mkdir -p /data/harvesters/sfoh/mobile/results
mkdir -p /data/harvesters/sfoh/mobile/source/backup
mkdir -p /data/harvesters/sfoh/mobile/source/archive
mkdir -p /data/harvesters/sfoh/mobile/source/working
mkdir -p /data/harvesters/sfoh/mobile/source/transients
mkdir -p /data/harvesters/sfoh/MWGMalware/source
mkdir -p /data/harvesters/sfoh/MWGMalware/results
mkdir -p /data/harvesters/sfoh/repper/source
mkdir -p /data/harvesters/sfoh/repper/results
mkdir -p /data/harvesters/sfoh/repper/source/temp
mkdir -p /data/harvesters/sfoh/repper/source/archive
mkdir -p /data/harvesters/sfoh/repper/source/working
mkdir -p /data/harvesters/sfoh/repper/source/archive/old
mkdir -p /data/harvesters/sfoh/repper/source/working/old
mkdir -p /data/harvesters/sfoh/socialmedia/results1
mkdir -p /data/harvesters/sfoh/socialmedia/source
mkdir -p /data/harvesters/sfoh/socialmedia/source1
mkdir -p /data/harvesters/sfoh/socialmedia/results
mkdir -p /data/harvesters/sfoh/socialmedia/source/archive
mkdir -p /data/harvesters/sfoh/socialmedia/source/working
mkdir -p /data/harvesters/sfoh/socialmedia/source1/archive
mkdir -p /data/harvesters/sfoh/socialmedia/source1/working
mkdir -p /data/harvesters/sfoh/wwuncat/source
mkdir -p /data/harvesters/sfoh/wwuncat/results
mkdir -p /data/harvesters/sfoh/wwuncat/source/archive
mkdir -p /data/harvesters/sfoh/wwuncat/source/working
mkdir -p /data/harvesters/McAfeeSecure/temp
mkdir -p /data/harvesters/McAfeeSecure/removal
mkdir -p /data/harvesters/McAfeeSecure/archive
mkdir -p /data/harvesters/McAfeeSecure/ashwini_backup
mkdir -p /data/harvesters/McAfeeSecure/temp/archive
mkdir -p /data/harvesters/blist_generator/transfer
mkdir -p /data/harvesters/repper/bak
mkdir -p /data/harvesters/bitdefender_export/archive
mkdir -p /data/harvesters/bitdefender_export/working
mkdir -p /data/harvesters/crawler/cleanmxvirus
mkdir -p /data/harvesters/crawler/CSirt
mkdir -p /data/harvesters/crawler/sampleDB
mkdir -p /data/harvesters/crawler/seo_test
mkdir -p /data/harvesters/crawler/cleanmxportal
mkdir -p /data/harvesters/crawler/recrawl
mkdir -p /data/harvesters/crawler/SEOTrends
mkdir -p /data/harvesters/crawler/marxav
mkdir -p /data/harvesters/crawler/scumware
mkdir -p /data/harvesters/crawler/cleanmxvirus/archive
mkdir -p /data/harvesters/crawler/cleanmxvirus/working
mkdir -p /data/harvesters/crawler/cleanmxvirus/results
mkdir -p /data/harvesters/crawler/sampleDB/source
mkdir -p /data/harvesters/crawler/recrawl/results
